
import type { Metadata } from "next";
import "./globals.css";
import GlobalWrapper from "./Provider";



export const metadata: Metadata = {
  title: "Naukari App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <GlobalWrapper>
          {children}
        </GlobalWrapper>

      </body>
    </html>
  );
}
